limit: 50
keybindings:
  run-query: "Ctrl-Space"
  structure: "Ctrl-S"
  indexes: "Ctrl-I"
  constraints: "Ctrl-T"
  clear-editor: "Ctrl-D"
  navigation:
    up: "Ctrl-K"
    down: "Ctrl-J"
    left: "Ctrl-H"
    right: "Ctrl-L"
