model = "gpt-5.6-sol"
model_reasoning_effort = "max"
[projects."/home/razen/projects/dotfiles"]
trust_level = "trusted"

[projects."/home/razen/projects/zmk-config"]
trust_level = "trusted"

[projects."/home/razen"]
trust_level = "trusted"

[projects."/home/razen/projects/bun-boilerplate"]
trust_level = "trusted"

[projects."/home/razen/projects"]
trust_level = "trusted"

[projects."/home/razen/projects/keebs"]
trust_level = "trusted"

[projects."/home/razen/projects/keebs/keyboards/src/cantor-ble"]
trust_level = "trusted"

[projects."/home/razen/projects/scaffold-embedded"]
trust_level = "trusted"

[projects."/home/razen/Downloads"]
trust_level = "trusted"

[projects."/home/razen/projects/mana2"]
trust_level = "trusted"

[projects."/home/razen/projects/csgo"]
trust_level = "trusted"

[projects."/home/razen/projects/cv"]
trust_level = "trusted"

[projects."/home/razen/projects/herdr.nvim"]
trust_level = "trusted"

[projects."/home/razen/projects/fleetpit"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4

[marketplaces.ponytail]
last_updated = "2026-07-10T13:41:42Z"
last_revision = "14a0d79548d4de8fc2de95c1b94bb0de63a739d3"
source_type = "git"
source = "https://github.com/DietrichGebert/ponytail.git"

[marketplaces.caveman]
last_updated = "2026-07-06T14:57:07Z"
last_revision = "0d95a81d35a9f2d123a5e9430d1cfc43d55f1bb0"
source_type = "git"
source = "https://github.com/JuliusBrussee/caveman.git"

[plugins."ponytail@ponytail"]
enabled = false

[plugins."caveman@caveman"]
enabled = false

[notice]
hide_rate_limit_model_nudge = true
